name: Go Backend CI/CD

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: macos-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.23"

            - name: Install Firebase CLI
              run: |
                  curl -sL https://firebase.tools | bash

            - name: Start Firestore Emulator
              run: |
                  nohup firebase emulators:start --only firestore --project chemtrack-3857a --port 8080 > /tmp/emulator.log 2>&1 &
                  # Poll the emulator until it's ready
                  until curl -s http://localhost:8080; do
                    echo "Waiting for Firestore Emulator to start..."
                    sleep 5
                  done

            - name: Install Dependencies
              working-directory: backend
              run: go mod tidy

            - name: Run Tests
              working-directory: backend
              run: go test ./tests

            - name: Stop Firestore Emulator and Clean Up
              run: |
                  # Find the process ID of the emulator and kill it
                  emulator_pid=$(ps aux | grep '[f]irebase' | awk '{print $2}')
                  if [ -n "$emulator_pid" ]; then
                    kill $emulator_pid
                    echo "Firestore Emulator stopped."
                  else
                    echo "No Firestore Emulator process found."
                  fi
                  # Clean up any environment variables
                  unset FIRESTORE_EMULATOR_HOST
                  unset ENVIRONMENT
