name: Go Backend CI/CD

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: macos-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.22"

            - name: Install Firebase CLI
              run: npm install -g firebase-tools

            - name: Start Firestore Emulator
              working-directory: backend
              run: |
                  nohup firebase emulators:start --only firestore --project chemtrack-3857a > /tmp/emulator.log 2>&1 &
                  for i in {1..10}; do
                    nc -z localhost 8080 && break
                    echo "Waiting for Firestore Emulator to be ready..."
                    sleep 3
                  done
                  nc -z localhost 8080 || (echo "Emulator failed to start." && cat /tmp/emulator.log && exit 1)

            - name: Install Dependencies
              working-directory: backend
              run: go mod tidy

            - name: Run Tests
              working-directory: backend
              env:
                  FIRESTORE_EMULATOR_HOST: localhost:8080
              run: go test -v ./tests

            - name: Stop Firestore Emulator and Clean Up
              if: always()
              run: |
                  emulator_pid=$(ps aux | grep '[f]irebase' | awk '{print $2}')
                  if [ -n "$emulator_pid" ]; then
                    kill $emulator_pid
                    echo "Firestore Emulator stopped."
                  else
                    echo "No Firestore Emulator process found."
                  fi
                  unset FIRESTORE_EMULATOR_HOST
                  unset ENVIRONMENT
